version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      ROUTER_SECRET: "ROUTER_SECRET"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Gjiroto12_
      MYSQL_DATABASE: inventory
    ports:
      - "3307:3306"