package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"graphql-inventario/graph/model"
)

// FindCellphoneByID is the resolver for the findCellphoneByID field.
func (r *entityResolver) FindCellphoneByID(ctx context.Context, id string) (*model.Cellphone, error) {
	panic(fmt.Errorf("not implemented: FindCellphoneByID - findCellphoneByID"))
}

// FindRefrigeratorByID is the resolver for the findRefrigeratorByID field.
func (r *entityResolver) FindRefrigeratorByID(ctx context.Context, id string) (*model.Refrigerator, error) {
	panic(fmt.Errorf("not implemented: FindRefrigeratorByID - findRefrigeratorByID"))
}

// FindTVByID is the resolver for the findTVByID field.
func (r *entityResolver) FindTVByID(ctx context.Context, id string) (*model.Tv, error) {
	panic(fmt.Errorf("not implemented: FindTVByID - findTVByID"))
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
